### ISSUE TITLE
Tag a new release to incorporate last patches?

### ISSUE THREAD

**Issue by holtkamp** [zf1s/zend-validate#2]
After upgrading PHP from `7.1` to `7.3`, some errors appeared when using Zend Framework 1 which have been fixed in the _master_ branch. 

Would it be a (good) idea to tag a new release? I guess this could be `1.12.21` since the last commits since `1.12.20` are patches?

**Comment by falkenhawk** [comment]
@holtkamp this is something I could not decide for yet ;) But since there is basically zero chance to see an official `1.12.21` release we might go with that. But maybe jump up to `1.13.x` already? Or maybe we should only add an additional suffix e.g. `1.12.20-1`, `1.12.20-2` etc.

**Comment by holtkamp** [comment]
>Or maybe we should only add an additional suffix e.g. `1.12.20-1`, `1.12.20-2` etc.

mmm, interesting, it seems that [Semantic Versioning](https://semver.org/) only allows that for pre-releases...

>But since there is basically zero chance to see an official `1.12.21` release we might go with that.

Indeed

>But maybe jump up to `1.13.x` already?

Well, I guess this is not required, since they are actually `PATCH` versions without any functional changes, right?

**Comment by dmnc** [comment]
I can see arguments both ways. `1.13.0` shows with great clarity the departure from the historical, official releases but also implies new features which may give people the wrong idea on a legacy support project.

If we're being strict, these are bugfixes and therefore SemVer requires that we use `1.12.21`.

**Comment by dmnc** [comment]
@unhawkable Do you have a preference? It would be wonderful to be able to get back on stable packages here.

**Comment by falkenhawk** [comment]
@dmnc I will get back to it as soon as possible, after my current errands. I am going to release 1.12.21. Thank you all for your valuable input.

**Comment by dmnc** [comment]
@unhawkable I'm sorry to be a pain here. I understand you're busy and do sympathise.

Getting these released really would be a big help for me. If you're struggling with time, I'd be happy to help out with this (and anything else that would be useful to keep zf1 working) if you can add me as a collaborator. I think now we have clarity that we're going for 1.12.21 it should all be a fairly straightforward process.

**Comment by falkenhawk** [comment]
@dmnc I'm sorry to be a showstopper here. I've just invited you to the organisation. I am also working on the releases right now. Should be ready soon.

**Comment by falkenhawk** [comment]
to anyone concerned: 1.13 is incoming with reorganized structure (monorepo), re-introduced tests (updated to work up to php 7.3) and few more bugfixes found along testing.

**Comment by holtkamp** [comment]
@falkenhawk that is some impressive work listed at https://github.com/zf1s/zf1/blob/master/CHANGELOG.md

Thanks!
